import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {attentionExperiment,softmax} from '../labs/attention-core.mjs';
import {poisonExperiment} from '../labs/poison-core.mjs';
import {capsuleMetrics} from '../labs/geometry-core.mjs';
import {validateBenchmark} from '../labs/benchmark-core.mjs';
const cases=[];
function test(name,fn){fn();cases.push({name,passed:true});}
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-10,`${a} != ${b}`);
test('Stable softmax preserves normalized probabilities for large logits',()=>{const p=softmax([1000,1001,1002]);close(p.reduce((a,b)=>a+b,0),1);assert.ok(p[2]>p[1]&&p[1]>p[0]);});
test('Both attention blocks normalize rows and mask all future positions',()=>{for(const l of attentionExperiment('trust AI').layers)l.attention.forEach((r,i)=>{close(r.reduce((a,b)=>a+b,0),1);r.forEach((v,j)=>{assert.ok(Number.isFinite(v)&&v>=0&&v<=1);if(j>i)assert.equal(v,0);});});});
test('Appending future tokens cannot alter earlier block outputs',()=>{const a=attentionExperiment('trust'),b=attentionExperiment('trust AI');a.layers.forEach((l,i)=>assert.deepEqual(l.output,b.layers[i].output.slice(0,5)));});
test('Changing input changes projections and second layer is distinct',()=>{const a=attentionExperiment('trust'),b=attentionExperiment('trace');assert.notDeepEqual(a.layers[0].Q,b.layers[0].Q);assert.notDeepEqual(a.layers[0].attention,a.layers[1].attention);});
test('Empty input, Unicode and token cap remain well-defined',()=>{assert.deepEqual(attentionExperiment('').layers,[]);assert.equal(attentionExperiment('😀').tokens.length,1);assert.equal(attentionExperiment('abcdefghijklmnop').tokens.length,12);});
test('Exported Q projection matches independent layer-normalization calculation',()=>{const a=attentionExperiment('audit'),r=a.layers[0].input[2],m=r.reduce((s,v)=>s+v,0)/8,variance=r.reduce((s,v)=>s+(v-m)**2,0)/8;for(let j=0;j<8;j++)close(a.layers[0].Q[2][j],r.reduce((s,v,k)=>s+(v-m)/Math.sqrt(variance+1e-5)*a.weights[0].WQ[k][j],0));});
test('Clean poisoning control classifies the known-A query correctly',()=>{const a=poisonExperiment(0,.35);assert.ok(a.meanProbability<.5&&a.medianProbability<.5);assert.deepEqual(a.b,a.cleanB);});
test('Minority poisoning flips the mean classifier while median resists',()=>{const a=poisonExperiment(1.5,.35);assert.ok(a.meanProbability>.5&&a.medianProbability<.5);close(a.boundary-poisonExperiment(0,.35).boundary,-1.5*.35/2);});
test('Majority contamination defeats the median defense',()=>assert.ok(poisonExperiment(2,.7).medianProbability>.5));
test('Poisoning controls reject invalid values',()=>{for(const v of [-1,3,NaN,Infinity])assert.throws(()=>poisonExperiment(v));assert.throws(()=>poisonExperiment(1,.9));});
test('Capsule volume matches cylinder plus sphere and reference discrepancy',()=>{const m=capsuleMetrics(.6);close(m.volume,Math.PI*.36*2.2+4*Math.PI*.216/3);close(m.axisLength,2.2);close(m.hausdorff,0);close(capsuleMetrics(.8).hausdorff,.2);assert.throws(()=>capsuleMetrics(0));});
const snapshot=JSON.parse(readFileSync(new URL('../data/drag-pilot.json',import.meta.url)));
test('Benchmark snapshot has 15 valid unique model-language cells',()=>{validateBenchmark(snapshot);assert.equal(snapshot.records.length,15);assert.equal(new Set(snapshot.records.map(r=>r.model+r.language)).size,15);});
test('All aggregate values agree with transcribed manuscript table',()=>{const expected={'gpt-3.5-turbo':[[1.2,15,2],[1.8,55,5],[1.7,25,8]],'gpt-4o':[[1.3,10,8],[4.1,30,16],[2.6,10,22]],'gpt-4o-mini':[[1.8,20,7],[3.9,35,16],[2.9,10,24]],'gpt-5':[[1.2,40,52],[4.9,20,96],[1.1,60,136]],'gpt-5.1':[[3.1,0,19],[4.7,15,27],[1.9,45,39]]};for(const r of snapshot.records){assert.deepEqual([r.arss,r.refusalPercent,r.latencySeconds],expected[r.model][['Chinese','English','Spanish'].indexOf(r.language)]);assert.equal(r.prompts,20);}});
test('Benchmark import rejects out-of-range and malformed records',()=>{for(const change of [{arss:7},{latencySeconds:-1},{refusalPercent:101},{language:'Unknown'},{prompts:0},{model:''}])assert.throws(()=>validateBenchmark({records:[{...snapshot.records[0],...change}]}));assert.throws(()=>validateBenchmark({records:[]}));});
const sources=['labs/attention-core.mjs','labs/poison-core.mjs','labs/geometry-core.mjs','labs/benchmark-core.mjs','data/drag-pilot.json','tests/check_workbench.mjs'];
const report={testedAt:new Date().toISOString(),scope:'Demo calculations and import validation only; not paper reproduction or production safety certification',total:cases.length,passed:cases.filter(c=>c.passed).length,cases,sha256:Object.fromEntries(sources.map(p=>[p,createHash('sha256').update(readFileSync(new URL('../'+p,import.meta.url))).digest('hex')]))};
writeFileSync(new URL('../data/workbench-checks.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
console.log(`${report.passed}/${report.total} calculation cases passed.`);
